include:
  - docker-compose.yml

services:
  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9095:9090'

  grafana:
    image: grafana/grafana:latest
    volumes:
      - ./monitoring/grafana-datasources:/etc/grafana/provisioning/datasources
      - ./monitoring/grafana-dashboards:/etc/grafana/provisioning/dashboards
    ports:
      - '3005:3000'
    depends_on:
      - prometheus
